run_number_1:
  C: 5
  dual: False
  model: "logistic_regression"
  solver: "saga"
  metric: "f1"
  penalty: "l1"
  max_iter: 2500
  random_state: 25

run_number_2:
  C: 5
  loss: "squared_hinge"
  dual: False
  model: "linear_svc"
  metric: "f1"
  penalty: "l1"
  max_iter: 5000
